name: json_server_api
description: A package to simulate an API built with Dart.
version: 1.0.3
homepage: https://flutterdicas.com.br/bootcamp
repository: https://github.com/alickbuscariolli/json_server_api

environment:
  sdk: ^3.0.0

# Add regular dependencies here.
dependencies:
  path: ^1.8.3
  args: ^2.4.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0

executables:
  jsonserverapi: main